export { socketManager } from "./SocketManager"
export { systemClientModule } from "./modules/system"
export { wifiClientModule } from "./modules/wifi"
export { bluetoothClientModule } from "./modules/bluetooth"
export { audioClientModule } from "./modules/audio"
export { storageClientModule } from "./modules/storage"
export type { SocketModule } from "./types"
