export { socketManager } from "./SocketManager"
export { systemClientModule } from "./modules/system"
export { wifiClientModule } from "./modules/wifi"
export { bluetoothClientModule } from "./modules/bluetooth"
export type { SocketModule } from "./types"
